name: dotenv_check
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.15.0
  http: ^1.4.0
  shared_preferences: ^2.2.2
  google_generative_ai: ^0.4.7 # This was the version that resolved before it worked
  json_annotation: ^4.9.0
  path_provider: ^2.1.3 # For accessing file system paths
  permission_handler: ^11.3.1 # For requesting storage permissions

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
