// lib/models/study_plan_models.dart
import 'package:json_annotation/json_annotation.dart';
import 'syllabus_analyzer_models.dart'; // Import existing models (Topic, Unit etc.)

part 'study_plan_models.g.dart'; // This file will be generated by build_runner

@JsonSerializable(explicitToJson: true)
class StudyPlan {
  final String planTitle;
  final int totalAllocatedTimeMinutesUserCommitment; // Renamed for clarity
  final DateTime deadline;
  final List<StudySession>
  sessions; // The generated list of topic-specific and revision sessions
  final int totalRevisionTimeMinutes; // Total time explicitly for revision

  @JsonKey(
    defaultValue: [],
  ) // List of topics that couldn't be scheduled by deadline
  final List<Topic> uncoveredTopics;

  StudyPlan({
    required this.planTitle,
    required this.totalAllocatedTimeMinutesUserCommitment, // Use the new name
    required this.deadline,
    required this.sessions,
    required this.totalRevisionTimeMinutes,
    this.uncoveredTopics = const [], // Initialize in constructor
  });

  factory StudyPlan.fromJson(Map<String, dynamic> json) =>
      _$StudyPlanFromJson(json);
  Map<String, dynamic> toJson() => _$StudyPlanToJson(this);
}

@JsonSerializable(explicitToJson: true)
class StudySession {
  final String
  unitName; // Name of the parent unit (or 'Revision' for general revision)
  final Topic?
  topic; // The topic/subtopic to study (nullable for revision sessions)
  final int allocatedTimeMinutes; // Time allocated to this specific session
  final DateTime?
  scheduledDate; // Date this session is planned for (if distributed)
  final bool isRevision; // Flag to indicate if this is a revision session
  final String?
  scheduledStartTime; // NEW: To store the precise start time (e.g., "09:00")

  StudySession({
    required this.unitName,
    this.topic, // Make topic nullable
    required this.allocatedTimeMinutes,
    this.scheduledDate,
    this.isRevision = false, // Default to false
    this.scheduledStartTime, // Initialize new field
  });

  factory StudySession.fromJson(Map<String, dynamic> json) =>
      _$StudySessionFromJson(json);
  Map<String, dynamic> toJson() => _$StudySessionToJson(this);
}
