// lib/models/study_plan_models.dart
import 'package:json_annotation/json_annotation.dart';
import 'syllabus_analyzer_models.dart'; // Import existing models (Topic, Unit etc.)

part 'study_plan_models.g.dart'; // This file will be generated by build_runner

@JsonSerializable(explicitToJson: true)
class StudyPlan {
  final String planTitle;
  final int totalAllocatedTimeMinutes; // Total time user wants to study
  final DateTime deadline;
  final List<StudySession> sessions; // The generated list of sessions

  StudyPlan({
    required this.planTitle,
    required this.totalAllocatedTimeMinutes,
    required this.deadline,
    required this.sessions,
  });

  factory StudyPlan.fromJson(Map<String, dynamic> json) =>
      _$StudyPlanFromJson(json);
  Map<String, dynamic> toJson() => _$StudyPlanToJson(this);
}

@JsonSerializable(explicitToJson: true)
class StudySession {
  final String unitName; // Name of the parent unit
  final Topic topic; // The topic/subtopic to study
  final int allocatedTimeMinutes; // Time allocated to this specific session
  final DateTime?
  scheduledDate; // Date this session is planned for (if distributed)

  StudySession({
    required this.unitName,
    required this.topic,
    required this.allocatedTimeMinutes,
    this.scheduledDate,
  });

  factory StudySession.fromJson(Map<String, dynamic> json) =>
      _$StudySessionFromJson(json);
  Map<String, dynamic> toJson() => _$StudySessionToJson(this);
}
